// constants/location.ts
export interface City {
  id: string;
  name: string;
}

export interface State {
  id: string;
  name: string;
  code: string;
  countryCode: string;
  cities: City[];
}

export interface Country {
  id: string;
  name: string;
  isoCode: string;
  states: State[];
}

export const COUNTRIES: Country[] = [
  {
    id: 'IN',
    name: 'India',
    isoCode: 'IN',
    states: [
      {
        id: 'AP',
        name: 'Andhra Pradesh',
        code: 'AP',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Amaravati' },
          { id: '002', name: 'Anantapur' },
          { id: '003', name: 'Chandragiri' },
          { id: '004', name: 'East Godavari' },
          { id: '005', name: 'Guntur' },
          { id: '006', name: 'Kadapa' },
          { id: '007', name: 'Kakinada' },
          { id: '008', name: 'Kurnool' },
          { id: '009', name: 'Krishna' },
          { id: '010', name: 'Machilipatnam' },
          { id: '011', name: 'Nellore' },
          { id: '012', name: 'Nandyal' },
          { id: '013', name: 'Ongole' },
          { id: '014', name: 'Rajahmundry' },
          { id: '015', name: 'Srikakulam' },
          { id: '016', name: 'Tirupati' },
          { id: '017', name: 'Visakhapatnam' },
          { id: '018', name: 'Vizianagaram' },
          { id: '019', name: 'Vijayawada' },
          { id: '020', name: 'West Godavari' },
        ],
      },
      {
        id: 'AR',
        name: 'Arunachal Pradesh',
        code: 'AR',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Anjaw' },
          { id: '002', name: 'Changlang' },
          { id: '003', name: 'Dibang Valley' },
          { id: '004', name: 'East Kameng' },
          { id: '005', name: 'East Siang' },
          { id: '006', name: 'Itanagar' },
          { id: '007', name: 'Kamle' },
          { id: '008', name: 'Kra Daadi' },
          { id: '009', name: 'Kurung Kumey' },
          { id: '010', name: 'Lepa Rada' },
          { id: '011', name: 'Lohit' },
          { id: '012', name: 'Longding' },
          { id: '013', name: 'Lower Dibang Valley' },
          { id: '014', name: 'Lower Siang' },
          { id: '015', name: 'Lower Subansiri' },
          { id: '016', name: 'Namsai' },
          { id: '017', name: 'Pakke-Kessang' },
          { id: '018', name: 'Papum Pare' },
          { id: '019', name: 'Shi-Yomi' },
          { id: '020', name: 'Siang' },
          { id: '021', name: 'Tawang' },
          { id: '022', name: 'Tirap' },
          { id: '023', name: 'Upper Siang' },
          { id: '024', name: 'Upper Subansiri' },
          { id: '025', name: 'West Kameng' },
          { id: '026', name: 'West Siang' },
        ],
      },
      {
        id: 'AS',
        name: 'Assam',
        code: 'AS',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Baksa' },
          { id: '002', name: 'Barpeta' },
          { id: '003', name: 'Bongaigaon' },
          { id: '004', name: 'Cachar' },
          { id: '005', name: 'Chirang' },
          { id: '006', name: 'Darrang' },
          { id: '007', name: 'Dhemaji' },
          { id: '008', name: 'Dhubri' },
          { id: '009', name: 'Dibrugarh' },
          { id: '010', name: 'Goalpara' },
          { id: '011', name: 'Golaghat' },
          { id: '012', name: 'Hailakandi' },
          { id: '013', name: 'Jorhat' },
          { id: '014', name: 'Kamrup' },
          { id: '015', name: 'Kamrup Metropolitan' },
          { id: '016', name: 'Karbi Anglong' },
          { id: '017', name: 'Karimganj' },
          { id: '018', name: 'Kokrajhar' },
          { id: '019', name: 'Lakhimpur' },
          { id: '020', name: 'Majuli' },
          { id: '021', name: 'Morigaon' },
          { id: '022', name: 'Nagaon' },
          { id: '023', name: 'Nalbari' },
          { id: '024', name: 'Sivasagar' },
          { id: '025', name: 'Sonitpur' },
          { id: '026', name: 'South Salmara-Mankachar' },
          { id: '027', name: 'Tinsukia' },
          { id: '028', name: 'Udalguri' },
          { id: '029', name: 'West Karbi Anglong' },
        ],
      },
      {
        id: 'BR',
        name: 'Bihar',
        code: 'BR',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Araria' },
          { id: '002', name: 'Arwal' },
          { id: '003', name: 'Aurangabad' },
          { id: '004', name: 'Banka' },
          { id: '005', name: 'Begusarai' },
          { id: '006', name: 'Bhagalpur' },
          { id: '007', name: 'Bhojpur' },
          { id: '008', name: 'Buxar' },
          { id: '009', name: 'Darbhanga' },
          { id: '010', name: 'East Champaran' },
          { id: '011', name: 'Gaya' },
          { id: '012', name: 'Gopalganj' },
          { id: '013', name: 'Jamui' },
          { id: '014', name: 'Jehanabad' },
          { id: '015', name: 'Kaimur' },
          { id: '016', name: 'Katihar' },
          { id: '017', name: 'Khagaria' },
          { id: '018', name: 'Kishanganj' },
          { id: '019', name: 'Lakhisarai' },
          { id: '020', name: 'Madhepura' },
          { id: '021', name: 'Madhubani' },
          { id: '022', name: 'Munger' },
          { id: '023', name: 'Muzaffarpur' },
          { id: '024', name: 'Nalanda' },
          { id: '025', name: 'Nawada' },
          { id: '026', name: 'Patna' },
          { id: '027', name: 'Purnia' },
          { id: '028', name: 'Rohtas' },
          { id: '029', name: 'Saharsa' },
          { id: '030', name: 'Samastipur' },
          { id: '031', name: 'Saran' },
          { id: '032', name: 'Sheikhpura' },
          { id: '033', name: 'Sheohar' },
          { id: '034', name: 'Sitamarhi' },
          { id: '035', name: 'Siwan' },
          { id: '036', name: 'Supaul' },
          { id: '037', name: 'Vaishali' },
          { id: '038', name: 'West Champaran' },
        ],
      },
      {
        id: 'CH',
        name: 'Chandigarh',
        code: 'CH',
        countryCode: 'IN',
        cities: [{ id: '001', name: 'Chandigarh' }],
      },
      {
        id: 'CG',
        name: 'Chhattisgarh',
        code: 'CG',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Balod' },
          { id: '002', name: 'Baloda Bazar' },
          { id: '003', name: 'Balrampur' },
          { id: '004', name: 'Bastar' },
          { id: '005', name: 'Bemetara' },
          { id: '006', name: 'Bijapur' },
          { id: '007', name: 'Bilaspur' },
          { id: '008', name: 'Dantewada' },
          { id: '009', name: 'Dhamtari' },
          { id: '010', name: 'Durg' },
          { id: '011', name: 'Gariaband' },
          { id: '012', name: 'Janjgir-Champa' },
          { id: '013', name: 'Jashpur' },
          { id: '014', name: 'Kabirdham' },
          { id: '015', name: 'Kanker' },
          { id: '016', name: 'Khairagarh-Chhuikhadan-Gandai' },
          { id: '017', name: 'Kondagaon' },
          { id: '018', name: 'Korba' },
          { id: '019', name: 'Korea' },
          { id: '020', name: 'Mahasamund' },
          { id: '021', name: 'Mungeli' },
          { id: '022', name: 'Narayanpur' },
          { id: '023', name: 'Raigarh' },
          { id: '024', name: 'Raipur' },
          { id: '025', name: 'Rajnandgaon' },
          { id: '026', name: 'Sukma' },
          { id: '027', name: 'Surajpur' },
          { id: '028', name: 'Surguja' },
        ],
      },
      {
        id: 'DN',
        name: 'Dadra and Nagar Haveli and Daman and Diu',
        code: 'DN',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Dadra and Nagar Haveli' },
          { id: '002', name: 'Daman' },
          { id: '003', name: 'Diu' },
        ],
      },
      {
        id: 'DL',
        name: 'Delhi',
        code: 'DL',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Central Delhi' },
          { id: '002', name: 'East Delhi' },
          { id: '003', name: 'New Delhi' },
          { id: '004', name: 'North Delhi' },
          { id: '005', name: 'North East Delhi' },
          { id: '006', name: 'North West Delhi' },
          { id: '007', name: 'Shahdara' },
          { id: '008', name: 'South Delhi' },
          { id: '009', name: 'South East Delhi' },
          { id: '010', name: 'South West Delhi' },
          { id: '011', name: 'West Delhi' },
        ],
      },
      {
        id: 'GA',
        name: 'Goa',
        code: 'GA',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'North Goa' },
          { id: '002', name: 'South Goa' },
        ],
      },
      {
        id: 'GJ',
        name: 'Gujarat',
        code: 'GJ',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Ahmedabad' },
          { id: '002', name: 'Amreli' },
          { id: '003', name: 'Anand' },
          { id: '004', name: 'Aravalli' },
          { id: '005', name: 'Banaskantha' },
          { id: '006', name: 'Bharuch' },
          { id: '007', name: 'Bhavnagar' },
          { id: '008', name: 'Botad' },
          { id: '009', name: 'Chhota Udaipur' },
          { id: '010', name: 'Dahod' },
          { id: '011', name: 'Dang' },
          { id: '012', name: 'Devbhoomi Dwarka' },
          { id: '013', name: 'Gandhinagar' },
          { id: '014', name: 'Gir Somnath' },
          { id: '015', name: 'Jamnagar' },
          { id: '016', name: 'Junagadh' },
          { id: '017', name: 'Kachchh' },
          { id: '018', name: 'Kheda' },
          { id: '019', name: 'Mahisagar' },
          { id: '020', name: 'Mehsana' },
          { id: '021', name: 'Morbi' },
          { id: '022', name: 'Narmada' },
          { id: '023', name: 'Navsari' },
          { id: '024', name: 'Panchmahal' },
          { id: '025', name: 'Patan' },
          { id: '026', name: 'Porbandar' },
          { id: '027', name: 'Rajkot' },
          { id: '028', name: 'Sabarkantha' },
          { id: '029', name: 'Surat' },
          { id: '030', name: 'Surendranagar' },
          { id: '031', name: 'Tapi' },
          { id: '032', name: 'Vadodara' },
          { id: '033', name: 'Valsad' },
        ],
      },
      {
        id: 'HR',
        name: 'Haryana',
        code: 'HR',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Ambala' },
          { id: '002', name: 'Bhiwani' },
          { id: '003', name: 'Charkhi Dadri' },
          { id: '004', name: 'Faridabad' },
          { id: '005', name: 'Fatehabad' },
          { id: '006', name: 'Gurugram' },
          { id: '007', name: 'Hisar' },
          { id: '008', name: 'Jhajjar' },
          { id: '009', name: 'Jind' },
          { id: '010', name: 'Kalanwala' },
          { id: '011', name: 'Kaithal' },
          { id: '012', name: 'Karnal' },
          { id: '013', name: 'Kurukshetra' },
          { id: '014', name: 'Mahendragarh' },
          { id: '015', name: 'Narnaul' },
          { id: '016', name: 'Nuh' },
          { id: '017', name: 'Palwal' },
          { id: '018', name: 'Panchkula' },
          { id: '019', name: 'Panipat' },
          { id: '020', name: 'Rewari' },
          { id: '021', name: 'Rohtak' },
          { id: '022', name: 'Sirsa' },
          { id: '023', name: 'Sonipat' },
          { id: '024', name: 'Yamunanagar' },
          { id: '025', name: 'Narnaund' },
        ],
      },
      {
        id: 'HP',
        name: 'Himachal Pradesh',
        code: 'HP',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Bilaspur' },
          { id: '002', name: 'Chamba' },
          { id: '003', name: 'Hamirpur' },
          { id: '004', name: 'Kangra' },
          { id: '005', name: 'Kinnaur' },
          { id: '006', name: 'Kullu' },
          { id: '007', name: 'Lahaul and Spiti' },
          { id: '008', name: 'Mandi' },
          { id: '009', name: 'Shimla' },
          { id: '010', name: 'Sirmaur' },
          { id: '011', name: 'Solan' },
          { id: '012', name: 'Una' },
        ],
      },
      {
        id: 'JK',
        name: 'Jammu and Kashmir',
        code: 'JK',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Anantnag' },
          { id: '002', name: 'Bandipora' },
          { id: '003', name: 'Baramulla' },
          { id: '004', name: 'Budgam' },
          { id: '005', name: 'Doda' },
          { id: '006', name: 'Ganderbal' },
          { id: '007', name: 'Jammu' },
          { id: '008', name: 'Kargil' },
          { id: '009', name: 'Kathua' },
          { id: '010', name: 'Kishtwar' },
          { id: '011', name: 'Kulgam' },
          { id: '012', name: 'Kupwara' },
          { id: '013', name: 'Poonch' },
          { id: '014', name: 'Pulwama' },
          { id: '015', name: 'Rajouri' },
          { id: '016', name: 'Ramban' },
          { id: '017', name: 'Reasi' },
          { id: '018', name: 'Samba' },
          { id: '019', name: 'Shopian' },
          { id: '020', name: 'Srinagar' },
          { id: '021', name: 'Udhampur' },
        ],
      },
      {
        id: 'JH',
        name: 'Jharkhand',
        code: 'JH',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Bokaro' },
          { id: '002', name: 'Chatra' },
          { id: '003', name: 'Deoghar' },
          { id: '004', name: 'Dhanbad' },
          { id: '005', name: 'Dumka' },
          { id: '006', name: 'East Singhbhum' },
          { id: '007', name: 'Garhwa' },
          { id: '008', name: 'Giridih' },
          { id: '009', name: 'Godda' },
          { id: '010', name: 'Gumla' },
          { id: '011', name: 'Hazaribagh' },
          { id: '012', name: 'Jamtara' },
          { id: '013', name: 'Khunti' },
          { id: '014', name: 'Kodarma' },
          { id: '015', name: 'Latehar' },
          { id: '016', name: 'Lohardaga' },
          { id: '017', name: 'Pakur' },
          { id: '018', name: 'Palamu' },
          { id: '019', name: 'Ramgarh' },
          { id: '020', name: 'Ranchi' },
          { id: '021', name: 'Sahibganj' },
          { id: '022', name: 'Seraikela Kharsawan' },
          { id: '023', name: 'Simdega' },
          { id: '024', name: 'West Singhbhum' },
        ],
      },
      {
        id: 'KA',
        name: 'Karnataka',
        code: 'KA',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Bagalkot' },
          { id: '002', name: 'Ballari' },
          { id: '003', name: 'Belagavi' },
          { id: '004', name: 'Bengaluru Rural' },
          { id: '005', name: 'Bengaluru Urban' },
          { id: '006', name: 'Bidar' },
          { id: '007', name: 'Chamarajanagar' },
          { id: '008', name: 'Chikkaballapura' },
          { id: '009', name: 'Chikkamagaluru' },
          { id: '010', name: 'Chitradurga' },
          { id: '011', name: 'Dakshina Kannada' },
          { id: '012', name: 'Davanagere' },
          { id: '013', name: 'Dharwad' },
          { id: '014', name: 'Gadag' },
          { id: '015', name: 'Hassan' },
          { id: '016', name: 'Haveri' },
          { id: '017', name: 'Kalaburagi' },
          { id: '018', name: 'Kodagu' },
          { id: '019', name: 'Kolar' },
          { id: '020', name: 'Koppal' },
          { id: '021', name: 'Mandya' },
          { id: '022', name: 'Mysuru' },
          { id: '023', name: 'Raichur' },
          { id: '024', name: 'Ramanagara' },
          { id: '025', name: 'Shivamogga' },
          { id: '026', name: 'Tumakuru' },
          { id: '027', name: 'Udupi' },
          { id: '028', name: 'Uttara Kannada' },
          { id: '029', name: 'Vijayanagara' },
          { id: '030', name: 'Vijayapura' },
          { id: '031', name: 'Yadgir' },
        ],
      },
      {
        id: 'KL',
        name: 'Kerala',
        code: 'KL',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Alappuzha' },
          { id: '002', name: 'Ernakulam' },
          { id: '003', name: 'Idukki' },
          { id: '004', name: 'Kannur' },
          { id: '005', name: 'Kasaragod' },
          { id: '006', name: 'Kollam' },
          { id: '007', name: 'Kottayam' },
          { id: '008', name: 'Kozhikode' },
          { id: '009', name: 'Malappuram' },
          { id: '010', name: 'Palakkad' },
          { id: '011', name: 'Pathanamthitta' },
          { id: '012', name: 'Thiruvananthapuram' },
          { id: '013', name: 'Thrissur' },
          { id: '014', name: 'Wayanad' },
        ],
      },
      {
        id: 'MP',
        name: 'Madhya Pradesh',
        code: 'MP',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Agar Malwa' },
          { id: '002', name: 'Alirajpur' },
          { id: '003', name: 'Anuppur' },
          { id: '004', name: 'Ashoknagar' },
          { id: '005', name: 'Balaghat' },
          { id: '006', name: 'Barwani' },
          { id: '007', name: 'Betul' },
          { id: '008', name: 'Bhind' },
          { id: '009', name: 'Bhopal' },
          { id: '010', name: 'Burhanpur' },
          { id: '011', name: 'Chhatarpur' },
          { id: '012', name: 'Chhindwara' },
          { id: '013', name: 'Damoh' },
          { id: '014', name: 'Datia' },
          { id: '015', name: 'Dewas' },
          { id: '016', name: 'Dhar' },
          { id: '017', name: 'Guna' },
          { id: '018', name: 'Gwalior' },
          { id: '019', name: 'Harda' },
          { id: '020', name: 'Hoshangabad' },
          { id: '021', name: 'Indore' },
          { id: '022', name: 'Jabalpur' },
          { id: '023', name: 'Jhabua' },
          { id: '024', name: 'Katni' },
          { id: '025', name: 'Khandwa' },
          { id: '026', name: 'Khargone' },
          { id: '027', name: 'Mandla' },
          { id: '028', name: 'Mandsaur' },
          { id: '029', name: 'Morena' },
          { id: '030', name: 'Narmadapuram' },
          { id: '031', name: 'Neemuch' },
          { id: '032', name: 'Niwari' },
          { id: '033', name: 'Panna' },
          { id: '034', name: 'Raisen' },
          { id: '035', name: 'Rajgarh' },
          { id: '036', name: 'Ratlam' },
          { id: '037', name: 'Rewa' },
          { id: '038', name: 'Sagar' },
          { id: '039', name: 'Satna' },
          { id: '040', name: 'Sehore' },
          { id: '041', name: 'Seoni' },
          { id: '042', name: 'Shahdol' },
          { id: '043', name: 'Shajapur' },
          { id: '044', name: 'Sheopur' },
          { id: '045', name: 'Shivpuri' },
          { id: '046', name: 'Sidhi' },
          { id: '047', name: 'Singrauli' },
          { id: '048', name: 'Tikamgarh' },
          { id: '049', name: 'Ujjain' },
          { id: '050', name: 'Umaria' },
          { id: '051', name: 'Vidisha' },
        ],
      },
      {
        id: 'MH',
        name: 'Maharashtra',
        code: 'MH',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Ahmednagar' },
          { id: '002', name: 'Akola' },
          { id: '003', name: 'Amravati' },
          { id: '004', name: 'Aurangabad' },
          { id: '005', name: 'Beed' },
          { id: '006', name: 'Bhandara' },
          { id: '007', name: 'Buldhana' },
          { id: '008', name: 'Chandrapur' },
          { id: '009', name: 'Dhule' },
          { id: '010', name: 'Gadchiroli' },
          { id: '011', name: 'Gondia' },
          { id: '012', name: 'Hingoli' },
          { id: '013', name: 'Jalgaon' },
          { id: '014', name: 'Jalna' },
          { id: '015', name: 'Kolhapur' },
          { id: '016', name: 'Latur' },
          { id: '017', name: 'Mumbai City' },
          { id: '018', name: 'Mumbai Suburban' },
          { id: '019', name: 'Nagpur' },
          { id: '020', name: 'Nanded' },
          { id: '021', name: 'Nandurbar' },
          { id: '022', name: 'Nashik' },
          { id: '023', name: 'Osmanabad' },
          { id: '024', name: 'Palghar' },
          { id: '025', name: 'Parbhani' },
          { id: '026', name: 'Pune' },
          { id: '027', name: 'Raigad' },
          { id: '028', name: 'Ratnagiri' },
          { id: '029', name: 'Sangli' },
          { id: '030', name: 'Satara' },
          { id: '031', name: 'Sindhudurg' },
          { id: '032', name: 'Solapur' },
          { id: '033', name: 'Thane' },
          { id: '034', name: 'Wardha' },
          { id: '035', name: 'Washim' },
          { id: '036', name: 'Yavatmal' },
        ],
      },
      {
        id: 'MN',
        name: 'Manipur',
        code: 'MN',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Bishnupur' },
          { id: '002', name: 'Chandel' },
          { id: '003', name: 'Churachandpur' },
          { id: '004', name: 'Imphal East' },
          { id: '005', name: 'Imphal West' },
          { id: '006', name: 'Jiribam' },
          { id: '007', name: 'Kakching' },
          { id: '008', name: 'Kamjong' },
          { id: '009', name: 'Kangpokpi' },
          { id: '010', name: 'Noney' },
          { id: '011', name: 'Pherzawl' },
          { id: '012', name: 'Senapati' },
          { id: '013', name: 'Tamenglong' },
          { id: '014', name: 'Tengnoupal' },
          { id: '015', name: 'Thoubal' },
          { id: '016', name: 'Ukhrul' },
        ],
      },
      {
        id: 'ML',
        name: 'Meghalaya',
        code: 'ML',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'East Garo Hills' },
          { id: '002', name: 'East Khasi Hills' },
          { id: '003', name: 'Eastern West Khasi Hills' },
          { id: '004', name: 'North Garo Hills' },
          { id: '005', name: 'Ri-Bhoi' },
          { id: '006', name: 'South Garo Hills' },
          { id: '007', name: 'South West Garo Hills' },
          { id: '008', name: 'South West Khasi Hills' },
          { id: '009', name: 'West Garo Hills' },
          { id: '010', name: 'West Khasi Hills' },
        ],
      },
      {
        id: 'MZ',
        name: 'Mizoram',
        code: 'MZ',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Aizawl' },
          { id: '002', name: 'Champhai' },
          { id: '003', name: 'Hnahthial' },
          { id: '004', name: 'Khawzawl' },
          { id: '005', name: 'Kolasib' },
          { id: '006', name: 'Lawngtlai' },
          { id: '007', name: 'Lunglei' },
          { id: '008', name: 'Mamit' },
          { id: '009', name: 'Saiha' },
          { id: '010', name: 'Saitual' },
          { id: '011', name: 'Serchhip' },
        ],
      },
      {
        id: 'NL',
        name: 'Nagaland',
        code: 'NL',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Chumoukedima' },
          { id: '002', name: 'Dimapur' },
          { id: '003', name: 'Kiphire' },
          { id: '004', name: 'Kohima' },
          { id: '005', name: 'Longleng' },
          { id: '006', name: 'Mokokchung' },
          { id: '007', name: 'Mon' },
          { id: '008', name: 'Niuland' },
          { id: '009', name: 'Noklak' },
          { id: '010', name: 'Peren' },
          { id: '011', name: 'Phek' },
          { id: '012', name: 'Shamator' },
          { id: '013', name: 'Tuensang' },
          { id: '014', name: 'Tseminyü' },
          { id: '015', name: 'Wokha' },
          { id: '016', name: 'Zunheboto' },
        ],
      },
      {
        id: 'OR',
        name: 'Odisha',
        code: 'OR',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Angul' },
          { id: '002', name: 'Balangir' },
          { id: '003', name: 'Balasore' },
          { id: '004', name: 'Bargarh' },
          { id: '005', name: 'Bhadrak' },
          { id: '006', name: 'Boudh' },
          { id: '007', name: 'Cuttack' },
          { id: '008', name: 'Deogarh' },
          { id: '009', name: 'Dhenkanal' },
          { id: '010', name: 'Gajapati' },
          { id: '011', name: 'Ganjam' },
          { id: '012', name: 'Jagatsinghpur' },
          { id: '013', name: 'Jajpur' },
          { id: '014', name: 'Jharsuguda' },
          { id: '015', name: 'Kalahandi' },
          { id: '016', name: 'Kandhamal' },
          { id: '017', name: 'Kendrapara' },
          { id: '018', name: 'Kendujhar' },
          { id: '019', name: 'Khordha' },
          { id: '020', name: 'Koraput' },
          { id: '021', name: 'Malkangiri' },
          { id: '022', name: 'Mayurbhanj' },
          { id: '023', name: 'Nabarangpur' },
          { id: '024', name: 'Nayagarh' },
          { id: '025', name: 'Nuapada' },
          { id: '026', name: 'Puri' },
          { id: '027', name: 'Rayagada' },
          { id: '028', name: 'Sambalpur' },
          { id: '029', name: 'Subarnapur' },
          { id: '030', name: 'Sundargarh' },
        ],
      },
      {
        id: 'PB',
        name: 'Punjab',
        code: 'PB',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Amritsar' },
          { id: '002', name: 'Barnala' },
          { id: '003', name: 'Bathinda' },
          { id: '004', name: 'Faridkot' },
          { id: '005', name: 'Fatehgarh Sahib' },
          { id: '006', name: 'Fazilka' },
          { id: '007', name: 'Firozpur' },
          { id: '008', name: 'Gurdaspur' },
          { id: '009', name: 'Hoshiarpur' },
          { id: '010', name: 'Jalandhar' },
          { id: '011', name: 'Kapurthala' },
          { id: '012', name: 'Ludhiana' },
          { id: '013', name: 'Malerkotla' },
          { id: '014', name: 'Mansa' },
          { id: '015', name: 'Moga' },
          { id: '016', name: 'Pathankot' },
          { id: '017', name: 'Patiala' },
          { id: '018', name: 'Rupnagar' },
          { id: '019', name: 'Sahibzada Ajit Singh Nagar' },
          { id: '020', name: 'Sangrur' },
          { id: '021', name: 'Shahid Bhagat Singh Nagar' },
          { id: '022', name: 'Sri Muktsar Sahib' },
          { id: '023', name: 'Tarn Taran' },
        ],
      },
      {
        id: 'RJ',
        name: 'Rajasthan',
        code: 'RJ',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Ajmer' },
          { id: '002', name: 'Alwar' },
          { id: '003', name: 'Anupgarh' },
          { id: '004', name: 'Banswara' },
          { id: '005', name: 'Baran' },
          { id: '006', name: 'Barmer' },
          { id: '007', name: 'Beawar' },
          { id: '008', name: 'Bikaner' },
          { id: '009', name: 'Bundi' },
          { id: '010', name: 'Chittorgarh' },
          { id: '011', name: 'Churu' },
          { id: '012', name: 'Dausa' },
          { id: '013', name: 'Dholpur' },
          { id: '014', name: 'Dungarpur' },
          { id: '015', name: 'Hanumangarh' },
          { id: '016', name: 'Jaipur' },
          { id: '017', name: 'Jaisalmer' },
          { id: '018', name: 'Jalore' },
          { id: '019', name: 'Jhalawar' },
          { id: '020', name: 'Jhunjhunu' },
          { id: '021', name: 'Jodhpur' },
          { id: '022', name: 'Karauli' },
          { id: '023', name: 'Kishangarh' },
          { id: '024', name: 'Kotputli-Behror' },
          { id: '025', name: 'Nagaur' },
          { id: '026', name: 'Pali' },
          { id: '027', name: 'Pratapgarh' },
          { id: '028', name: 'Rajsamand' },
          { id: '029', name: 'Salumbar' },
          { id: '030', name: 'Sanchore' },
          { id: '031', name: 'Sawai Madhopur' },
          { id: '032', name: 'Shahpura' },
          { id: '033', name: 'Sikar' },
          { id: '034', name: 'Sri Ganganagar' },
          { id: '035', name: 'Tonk' },
          { id: '036', name: 'Udaipur' },
        ],
      },
      {
        id: 'SK',
        name: 'Sikkim',
        code: 'SK',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Gangtok' },
          { id: '002', name: 'Mangan' },
          { id: '003', name: 'Namchi' },
          { id: '004', name: 'Gyalshing' },
        ],
      },
      {
        id: 'TN',
        name: 'Tamil Nadu',
        code: 'TN',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Ariyalur' },
          { id: '002', name: 'Chengalpattu' },
          { id: '003', name: 'Chennai' },
          { id: '004', name: 'Coimbatore' },
          { id: '005', name: 'Cuddalore' },
          { id: '006', name: 'Dharmapuri' },
          { id: '007', name: 'Dindigul' },
          { id: '008', name: 'Erode' },
          { id: '009', name: 'Kallakurichi' },
          { id: '010', name: 'Kanchipuram' },
          { id: '011', name: 'Kanyakumari' },
          { id: '012', name: 'Karur' },
          { id: '013', name: 'Krishnagiri' },
          { id: '014', name: 'Madurai' },
          { id: '015', name: 'Mayiladuthurai' },
          { id: '016', name: 'Nagapattinam' },
          { id: '017', name: 'Namakkal' },
          { id: '018', name: 'Nilgiris' },
          { id: '019', name: 'Perambalur' },
          { id: '020', name: 'Pudukkottai' },
          { id: '021', name: 'Ramanathapuram' },
          { id: '022', name: 'Ranipet' },
          { id: '023', name: 'Salem' },
          { id: '024', name: 'Sivaganga' },
          { id: '025', name: 'Tenkasi' },
          { id: '026', name: 'Thanjavur' },
          { id: '027', name: 'Theni' },
          { id: '028', name: 'Thoothukudi' },
          { id: '029', name: 'Tiruchirappalli' },
          { id: '030', name: 'Tirunelveli' },
          { id: '031', name: 'Tirupathur' },
          { id: '032', name: 'Tiruvallur' },
          { id: '033', name: 'Tiruvannamalai' },
          { id: '034', name: 'Tiruvarur' },
          { id: '035', name: 'Vellore' },
          { id: '036', name: 'Viluppuram' },
          { id: '037', name: 'Virudhunagar' },
        ],
      },
      {
        id: 'TG',
        name: 'Telangana',
        code: 'TG',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Adilabad' },
          { id: '002', name: 'Bhadradri Kothagudem' },
          { id: '003', name: 'Hyderabad' },
          { id: '004', name: 'Jagtial' },
          { id: '005', name: 'Jangaon' },
          { id: '006', name: 'Jayashankar Bhupalpally' },
          { id: '007', name: 'Jogulamba Gadwal' },
          { id: '008', name: 'Kamareddy' },
          { id: '009', name: 'Karimnagar' },
          { id: '010', name: 'Khammam' },
          { id: '011', name: 'Komaram Bheem Asifabad' },
          { id: '012', name: 'Mahabubabad' },
          { id: '013', name: 'Mahabubnagar' },
          { id: '014', name: 'Mancherial' },
          { id: '015', name: 'Medak' },
          { id: '016', name: 'Medchal-Malkajgiri' },
          { id: '017', name: 'Mulugu' },
          { id: '018', name: 'Nagarkurnool' },
          { id: '019', name: 'Nalgonda' },
          { id: '020', name: 'Narayanpet' },
          { id: '021', name: 'Nirmal' },
          { id: '022', name: 'Nizamabad' },
          { id: '023', name: 'Peddapalli' },
          { id: '024', name: 'Rajanna Sircilla' },
          { id: '025', name: 'Ranga Reddy' },
          { id: '026', name: 'Sangareddy' },
          { id: '027', name: 'Siddipet' },
          { id: '028', name: 'Suryapet' },
          { id: '029', name: 'Vikarabad' },
          { id: '030', name: 'Wanaparthy' },
          { id: '031', name: 'Warangal Rural' },
          { id: '032', name: 'Warangal Urban' },
          { id: '033', name: 'Yadadri Bhuvanagiri' },
        ],
      },
      {
        id: 'TR',
        name: 'Tripura',
        code: 'TR',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Dhalai' },
          { id: '002', name: 'Gomati' },
          { id: '003', name: 'Khowai' },
          { id: '004', name: 'North Tripura' },
          { id: '005', name: 'Sepahijala' },
          { id: '006', name: 'South Tripura' },
          { id: '007', name: 'Unakoti' },
          { id: '008', name: 'West Tripura' },
        ],
      },
      {
        id: 'UP',
        name: 'Uttar Pradesh',
        code: 'UP',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Agra' },
          { id: '002', name: 'Aligarh' },
          { id: '003', name: 'Ambedkar Nagar' },
          { id: '004', name: 'Amethi' },
          { id: '005', name: 'Amroha' },
          { id: '006', name: 'Auraiya' },
          { id: '007', name: 'Ayodhya' },
          { id: '008', name: 'Azamgarh' },
          { id: '009', name: 'Baghpat' },
          { id: '010', name: 'Bahraich' },
          { id: '011', name: 'Ballia' },
          { id: '012', name: 'Balrampur' },
          { id: '013', name: 'Banda' },
          { id: '014', name: 'Barabanki' },
          { id: '015', name: 'Bareilly' },
          { id: '016', name: 'Basti' },
          { id: '017', name: 'Bhadohi' },
          { id: '018', name: 'Bijnor' },
          { id: '019', name: 'Budaun' },
          { id: '020', name: 'Bulandshahr' },
          { id: '021', name: 'Chandauli' },
          { id: '022', name: 'Chitrakoot' },
          { id: '023', name: 'Deoria' },
          { id: '024', name: 'Etah' },
          { id: '025', name: 'Etawah' },
          { id: '026', name: 'Farrukhabad' },
          { id: '027', name: 'Fatehpur' },
          { id: '028', name: 'Firozabad' },
          { id: '029', name: 'Gautam Buddha Nagar' },
          { id: '030', name: 'Ghaziabad' },
          { id: '031', name: 'Ghazipur' },
          { id: '032', name: 'Gonda' },
          { id: '033', name: 'Gorakhpur' },
          { id: '034', name: 'Hamirpur' },
          { id: '035', name: 'Hapur' },
          { id: '036', name: 'Hardoi' },
          { id: '037', name: 'Hathras' },
          { id: '038', name: 'Jalaun' },
          { id: '039', name: 'Jaunpur' },
          { id: '040', name: 'Jhansi' },
          { id: '041', name: 'Kannauj' },
          { id: '042', name: 'Kanpur Dehat' },
          { id: '043', name: 'Kanpur Nagar' },
          { id: '044', name: 'Kasganj' },
          { id: '045', name: 'Kaushambi' },
          { id: '046', name: 'Kheri' },
          { id: '047', name: 'Kushinagar' },
          { id: '048', name: 'Lalitpur' },
          { id: '049', name: 'Lucknow' },
          { id: '050', name: 'Maharajganj' },
          { id: '051', name: 'Mahoba' },
          { id: '052', name: 'Mainpuri' },
          { id: '053', name: 'Mathura' },
          { id: '054', name: 'Mau' },
          { id: '055', name: 'Meerut' },
          { id: '056', name: 'Mirzapur' },
          { id: '057', name: 'Moradabad' },
          { id: '058', name: 'Muzaffarnagar' },
          { id: '059', name: 'Pilibhit' },
          { id: '060', name: 'Pratapgarh' },
          { id: '061', name: 'Prayagraj' },
          { id: '062', name: 'Raebareli' },
          { id: '063', name: 'Rampur' },
          { id: '064', name: 'Saharanpur' },
          { id: '065', name: 'Sambhal' },
          { id: '066', name: 'Sant Kabir Nagar' },
          { id: '067', name: 'Shahjahanpur' },
          { id: '068', name: 'Shamli' },
          { id: '069', name: 'Shravasti' },
          { id: '070', name: 'Siddharthnagar' },
          { id: '071', name: 'Sitapur' },
          { id: '072', name: 'Sonbhadra' },
          { id: '073', name: 'Sultanpur' },
          { id: '074', name: 'Unnao' },
          { id: '075', name: 'Varanasi' },
        ],
      },
      {
        id: 'UT',
        name: 'Uttarakhand',
        code: 'UT',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Almora' },
          { id: '002', name: 'Bageshwar' },
          { id: '003', name: 'Chamoli' },
          { id: '004', name: 'Champawat' },
          { id: '005', name: 'Dehradun' },
          { id: '006', name: 'Haridwar' },
          { id: '007', name: 'Nainital' },
          { id: '008', name: 'Pauri Garhwal' },
          { id: '009', name: 'Pithoragarh' },
          { id: '010', name: 'Rudraprayag' },
          { id: '011', name: 'Tehri Garhwal' },
          { id: '012', name: 'Udham Singh Nagar' },
          { id: '013', name: 'Uttarkashi' },
        ],
      },
      {
        id: 'WB',
        name: 'West Bengal',
        code: 'WB',
        countryCode: 'IN',
        cities: [
          { id: '001', name: 'Alipurduar' },
          { id: '002', name: 'Bankura' },
          { id: '003', name: 'Birbhum' },
          { id: '004', name: 'Cooch Behar' },
          { id: '005', name: 'Dakshin Dinajpur' },
          { id: '006', name: 'Darjeeling' },
          { id: '007', name: 'Hooghly' },
          { id: '008', name: 'Howrah' },
          { id: '009', name: 'Jalpaiguri' },
          { id: '010', name: 'Jhargram' },
          { id: '011', name: 'Kalimpong' },
          { id: '012', name: 'Kolkata' },
          { id: '013', name: 'Malda' },
          { id: '014', name: 'Murshidabad' },
          { id: '015', name: 'Nadia' },
          { id: '016', name: 'North 24 Parganas' },
          { id: '017', name: 'Paschim Bardhaman' },
          { id: '018', name: 'Paschim Medinipur' },
          { id: '019', name: 'Purba Bardhaman' },
          { id: '020', name: 'Purba Medinipur' },
          { id: '021', name: 'Purulia' },
          { id: '022', name: 'South 24 Parganas' },
          { id: '023', name: 'Uttar Dinajpur' },
        ],
      },
    ],
  },
];

// Helper functions
export const getStatesByCountry = (countryCode: string): State[] => {
  const country = COUNTRIES.find((c) => c.isoCode === countryCode);
  return country?.states || [];
};

export const getCitiesByState = (countryCode: string, stateCode: string): City[] => {
  const country = COUNTRIES.find((c) => c.isoCode === countryCode);
  const state = country?.states.find((s) => s.code === stateCode);
  return state?.cities || [];
};

export const getStateByCode = (countryCode: string, stateCode: string): State | undefined => {
  const country = COUNTRIES.find((c) => c.isoCode === countryCode);
  return country?.states.find((s) => s.code === stateCode);
};
